name: demo_data
language: python
variables:
  - name: test
    inputType: Secret
    description: test
    defaultValue: finhub_token
    required: false
  - name: test2
    inputType: Secret
    description: ''
    defaultValue: finhub_token
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
